### ISSUE TITLE
Add success indicator when adding a repo

### ISSUE THREAD

**Issue by JesseRWeigel** [javascript-af/javascript-af#33]
When you click submit to add a new repo there is no indication that the submission was successful. The best way to handle this may be to take the user back to the "Your Repositories" page and instead of a "Select" button next to each repo, add replace with an icon, maybe a checkmark next to every repo that has already been added.

**Comment by pantharshit00** [comment]
It will be difficult to filter that much repos out. 

Will look to this after the beta

**Comment by pantharshit00** [comment]
Now we redirect to the newly create repo's full page. Closing this issue
