### ISSUE TITLE
Big fix in user page related to UI

### ISSUE THREAD

**Issue by NickyMeuleman** [javascript-af/javascript-af#40]
Container for User-info (picture etc) on the `/user:id`-page is smaller than the content it contains on large screens.

**Comment by pantharshit00** [comment]
Not sure what are you saying. Screenshots?

**Comment by NickyMeuleman** [comment]
Screenshot of what I mean:
![chrome_2018-05-10_14-34-56](https://user-images.githubusercontent.com/30179461/39869832-57dc039e-545f-11e8-9ea1-33d8ff124684.png)

**Comment by pantharshit00** [comment]
Gotbit
